name: CI

on:
    workflow_dispatch:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    GITHUB_ACTIONS: true

jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.head_ref || github.ref_name }}
            cancel-in-progress: true

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 8.0.x

            -   name: Tool Restore
                run: dotnet tool restore

            -   name: Build
                run: dotnet build --configuration Release

            -   name: Tests
                run: dotnet test --configuration Release
